<a href="https://colab.research.google.com/github/bollitulasi/collab/blob/main/Numpy_full_topic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** CONTENT**

*introductio to numpy
*installlation of numpy
*importing numpy
* creating array
*initialization of array
*array properties
*array operations
* array functions

              CREATING ARRAYS  
            
      *array()
          .0 dimensinal aray
          .1 dimensiona array
          .2 dimensional arrray
          .3 dimensional array
       *as array()withnditer()
       *frombuffer()
       *fromiter()

In [ ]:
import numpy  as np

In [ ]:
a=np.array(10)
print(a)
#0 dimensional array

10


In [ ]:
a=np.array([10, 20, 30])
#1dimensional array
print(a)

[10 20 30]


In [ ]:

#2dimensional array
a=np.array([[10, 20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [ ]:
a=np.array([[[10, 20], [30, 40]],[[50,60],[70,80]]])
print(a)
#3dimensional array

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [ ]:
a=np.array([[[10, 20], [30, 40]],[[50,60],[70,80]]])

#3dimensional array
a[0][1][0]

30

In [ ]:
#asarray
a=[10, 20,30,]
a=np.asarray(a,dtype=float)
print(a)

[10. 20. 30.]


In [ ]:
#as array with 2dimensions arrays of rows&column
a=([[10, 20], [30, 40]])
b=np.asarray(a,dtype=float,order='C')
#C   mean row major order
print(b)
for i in np.nditer(b):
  print(i)

[[10. 20.]
 [30. 40.]]
10.0
20.0
30.0
40.0


In [ ]:
#as array with 2dimensions arrays of rows&column
a=([[10, 20], [30, 40]])
b=np.asarray(a,dtype=float,order='F')
#F mean column   major order
print(b)
for i in np.nditer(b):
  print(i)

[[10. 20.]
 [30. 40.]]
10.0
30.0
20.0
40.0


In [ ]:
#from  buffer
a=b"welcome to numpy"#as default it stored as ini
np.frombuffer(a)

array([1.27850763e-152, 9.10016855e+276])

In [ ]:
#from  buffer
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1")

array([b'w', b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't', b'o', b' ',
       b'n', b'u', b'm', b'p', b'y'], dtype='|S1')

In [ ]:
#from  buffer
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1",count=10)

array([b'w', b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't', b'o'],
      dtype='|S1')

In [ ]:
#from  buffer
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1",offset=9)

array([b'o', b' ', b'n', b'u', b'm', b'p', b'y'], dtype='|S1')

In [ ]:
#from  buffer
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1",count=2,offset=9)

array([b'o', b' '], dtype='|S1')

In [ ]:
#fromiter
a=[10,40,20,30]
np.fromiter(a, dtype=int)

array([10, 40, 20, 30])

    INITIALIZATION OF ARRAYS

     1.zeros()
     2.full()
     3.random.rand()
     4 ones()
     5 eye()
     6.numerical ranges()
         >arange()
         >linspace()
         > logspace()

In [ ]:
a=np.zeros(3)#zeros
print (a)

[0. 0. 0.]


In [ ]:
a=np.zeros([2, 3])
print (a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.zeros([2, 3,3])
print (a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#np.full
np. full([2, 3],1)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
#np.full
np. full([2, 3,4],10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [ ]:
#np.random.rand()
np.random.rand(2,3)

array([[0.09620266, 0.31229269, 0.25892107],
       [0.20878386, 0.25749633, 0.78123368]])

In [ ]:
#np.random.rand()
np.random.rand(2,3,3)

array([[[0.52007972, 0.13631124, 0.78416325],
        [0.1913876 , 0.08197236, 0.68040372],
        [0.58089137, 0.55270456, 0.44889384]],

       [[0.54436498, 0.74466616, 0.10875379],
        [0.69661275, 0.08885462, 0.24288136],
        [0.3162143 , 0.1225352 , 0.06783514]]])

In [ ]:
#np.ones()
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#np.eye()
np. eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
#np.eye()
np. eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#np.arange
a=np.arange(10, 20,1)
print (a)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
#np.arange
a=np.arange(0, 100,10,dtype=float)
print (a)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [ ]:
#reshape is an function

a. reshape(2, 3)

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
a.reshape (3, 2)#3, 2meams 3rows 2columns3*2=6

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
a=np.arange(10,130,10)
a.reshape(2,3,2)


array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60]],

       [[ 70,  80],
        [ 90, 100],
        [110, 120]]])

In [ ]:
#linspace
np.linspace(10, 100,10) #range with last elements

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
#linspace
np.linspace(10, 100,10,endpoint=False,retstep=True)

(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)

In [ ]:
#linspace
np.linspace(10, 100,10,endpoint=False,retstep=True,dtype=int)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)

In [ ]:
#logspace
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [ ]:
#logspace
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [ ]:
#logspace
np.logspace(1,10,10)#by default base is 10

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [ ]:
#logspace
np.logspace(1,10,10,base=2,dtype=int)#last option as data type is taken

array([   2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

    ARRAY PROPERTIES

  >SIZE- np.size(array)
  >SHAPE-np.shape(array)
  >DTYPE-np.dtype(array)

In [ ]:
a=np.arange(10,100,10)#in one array we can know about the shape &size&dtype is array properties
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
a=a.reshape(3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
np.size(a)

9

In [ ]:
np.shape(a)

(3, 3)

In [ ]:
a.dtype

dtype('int64')

               ARRAY OPERATIONS

>accessing&slicing operations
>copy()
>view
>sort()
>reshape()
>append()
>insert()
>delete()
>concatenate()
>stack()
>vstack()
>hstack()
>dstack()
>split()
>where()
>searchsorted()


In [ ]:
a=np.array([[10,20,30],[40,50,60]])#ACCESING&SLICING OPERATIONS
a

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
a[0]
a[0][1]

20

In [ ]:
s=np.arange(10,100,10)
s
s[2:5]

array([30, 40, 50])

In [ ]:
#copy

b=s.reshape(3,3)
a=np.copy(b)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
#VIEW
c=a.view()
print(c)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#sort
a=np.array([30,40,50,10,20])
np.sort(a)#ascending order

array([10, 20, 30, 40, 50])

In [ ]:
a=([[40,30,20],[10,50,60]])
np.sort(a,)#by default axis=1

array([[20, 30, 40],
       [10, 50, 60]])

In [ ]:
a=([[40,30,20],[10,50,60]])
np.sort(a,axis=0)#when we given axis=0 row wise sorting will be done

array([[10, 30, 20],
       [40, 50, 60]])

In [ ]:
np.sort(a)

array([[20, 30, 40],
       [10, 50, 60]])

In [ ]:
#it is an another type of sorting where we use dtype at the time of creating array
d=np.dtype([('name','S1'),('perc',float)])
marks=np.array([("ramu",95.0),("hari",75.6),("anu",98.3)],dtype=d)
marks

array([(b'r', 95. ), (b'h', 75.6), (b'a', 98.3)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks,order="name")

array([(b'a', 98.3), (b'h', 75.6), (b'r', 95. )],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
np.sort(marks,order="perc")

array([(b'h', 75.6), (b'r', 95. ), (b'a', 98.3)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [ ]:
a=np.arange(10,130,10)
a.reshape(2,3,2)#reshape is same as above


array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60]],

       [[ 70,  80],
        [ 90, 100],
        [110, 120]]])

In [ ]:
#append
a=np.array([10,20,30])#in single dimensinal array
b=np.array([40,50,60])
np.append(a,b)

array([10, 20, 30, 40, 50, 60])

In [ ]:
#multi dimensional array converts to single dimensional array
a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
np.append(a,b).reshape(4,2)


array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [ ]:
#insert
a


array([[10, 20],
       [30, 40]])

In [ ]:
np.insert(a,3,35)

array([10, 20, 30, 35, 40])

In [ ]:
np.insert(a,3,[35,45]).reshape(2,3)

array([[10, 20, 30],
       [35, 45, 40]])

In [ ]:
#delete
a
np.delete(a,2)

array([10, 20, 40])

In [ ]:
#concatenate
a=([[10,20],[30,40]])
b=([[50,60],[70,80]])
np.concatenate((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [ ]:
np.concatenate((a,b),axis=1)#row wise concatenation wil be done

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [ ]:
a,b

([[10, 20], [30, 40]], [[50, 60], [70, 80]])

In [ ]:
#stack
res=np.stack((a,b))#in concatenation and stack the index values are not same
res

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [ ]:
res[0]

array([[10, 20],
       [30, 40]])

In [ ]:
res[1]

array([[50, 60],
       [70, 80]])

In [ ]:
np.stack((a,b),axis=1)#row wise

array([[[10, 20],
        [50, 60]],

       [[30, 40],
        [70, 80]]])

In [ ]:
#vstack-vertical stack
np.vstack((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [ ]:
#h stack-horizontal stack
np.hstack((a,b))

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [ ]:
#d stack
np.dstack((a,b))

array([[[10, 50],
        [20, 60]],

       [[30, 70],
        [40, 80]]])

In [ ]:
#split
x=np.arange(10,110,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.split(x,2)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]

In [ ]:
np.split(x,3)

In [ ]:
z=np.split(x,5)
z

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

In [ ]:
S1,S2,S3,S4,S5=np.split(x,5)

In [ ]:
S1

array([10, 20])

In [ ]:
S3

array([50, 60])

In [ ]:
S5

array([ 90, 100])

In [ ]:
x=np.arange(10,130,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [ ]:
np.split(x,(4,3))

[array([10, 20, 30, 40]),
 array([], dtype=int64),
 array([ 40,  50,  60,  70,  80,  90, 100, 110, 120])]

In [ ]:
np.split(x,(2,6))

[array([10, 20]),
 array([30, 40, 50, 60]),
 array([ 70,  80,  90, 100, 110, 120])]

In [ ]:
#where
a=np.arange(10,130,10).reshape(4,3)
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [ ]:
np.where(a==80)

(array([2]), array([1]))

In [ ]:
b=np.arange(10,100,20)
b

array([10, 30, 50, 70, 90])

In [ ]:
np.where(b==50)

(array([2]),)

In [ ]:
a
np.where(a%20==0)

(array([0, 1, 1, 2, 3, 3]), array([1, 0, 2, 1, 0, 2]))

In [ ]:
#seachsorted
a=np.array([10,20,30,40,50,60])
np.searchsorted(a,40)

3

In [ ]:
np.searchsorted(a,[40,50])

array([3, 4])

            ARITHMETIC OPERATIONS

      1.add()
      2.subtract()
      3.multiply()
      4.divide()
      5.exp()
      6.sqrt()
    >comparison

In [ ]:
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[1,2,3],[4,5,6]])
a
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.add(a,b)

array([[11, 22, 33],
       [44, 55, 66]])

In [ ]:
c=([[10,20],[3,4]])
np.add(a,c)

In [ ]:
np.subtract(a,b)

array([[ 9, 18, 27],
       [36, 45, 54]])

In [ ]:
np.divide(a,b)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 360]])

In [ ]:
np.exp(a)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26]])

In [ ]:
np.sqrt(a)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669]])

In [ ]:
#comparison
a=([[10,20,30],[40,50,60]])
b=([[1,2,3],[4,5,6]])
b

[[1, 2, 3], [4, 5, 6]]

In [ ]:
b[1][0]=40
b[1][1]=50
b[1][2]=60
b

[[1, 2, 3], [40, 50, 60]]

In [ ]:
np.array_equal(a,b)

False

In [ ]:
a==b

False

ARRAY FUNCTIONS

1.sum()
2.min()
3.max()
4.mean()
5.median()
6.var()
7.std()

In [ ]:
a=([[10,20],[30,40],[50,60]])
a

[[10, 20], [30, 40], [50, 60]]

In [ ]:
np.min(a)

10

In [ ]:
np.min(a,axis=1)#row

array([10, 30, 50])

In [ ]:
np.min(a,axis=0)#column

array([10, 20])

In [ ]:
np.max(a)

60

In [ ]:
np.max(a,axis=0)

array([50, 60])

In [ ]:
np.max(a,axis=1)

array([20, 40, 60])

In [ ]:
np.sum(a)

210

In [ ]:
np.sum(a,axis=0)

array([ 90, 120])

In [ ]:
np.sum(a,axis=1)

array([ 30,  70, 110])

In [ ]:
np.mean(a)

35.0

In [ ]:
np.mean(a,axis=0)

array([30., 40.])

In [ ]:
np.mean(a,axis=1)

array([15., 35., 55.])

In [ ]:
np.median(1)

1.0

In [ ]:
np.median(a,axis=0)

array([30., 40.])

In [ ]:
np.median(a,axis=1)

array([15., 35., 55.])

In [ ]:
np.var(a)

291.6666666666667

In [ ]:
np.var(a,axis=0)

array([266.66666667, 266.66666667])

In [ ]:
np.var(a,axis=1)

array([25., 25., 25.])

In [ ]:
np.std(a)

17.07825127659933

In [ ]:
np.std(a,axis=0)

array([16.32993162, 16.32993162])

In [ ]:
np.std(a,axis=1)

array([5., 5., 5.])